kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: pfcon-pman-openshift
  annotations:
    description: Creates pfcon and pman on OpenShift
    tags: ""
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: pfcon-new
      labels:
        app: pfcon-new
        env: test
    spec:
      selector:
        app: pfcon-new
        env: test
      ports:
        - name: 30005-tcp
          port: 30005
          targetPort: 30005

  - apiVersion: v1
    kind: Route
    metadata:
      name: pfcon-new
    spec:
      port:
        targetPort: 30005-tcp
      to:
        kind: Service
        name: pfcon-new
        weight: 100
        
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: pfcon-new
      labels:
        app: pfcon-new
        env: test
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: pfcon-new
          env: test
      template:
        metadata:
          name: pfcon-new
          labels:
            app: pfcon-new
            env: test
        spec:
          initContainers:
            - name: init-pfcon
              image: busybox:1.32
              command: [ "sh", "-c", "until wget --spider -S -T 2 http://pman-new:5010/api/v1/ 2>&1 | grep '200 OK'; do echo waiting for pman; done" ]
          containers:
            - name: pfcon-new
              image: fnndsc/pfcon
              imagePullPolicy: Always
              ports:
                - containerPort: 30005
              env:
                - name: COMPUTE_SERVICE_URL
                  value: http://pman-new:5010/api/v1/
                - name: PFCON_USER
                  valueFrom:
                    secretKeyRef:
                      name: pfcon-secret
                      key: PFCON_USER
                - name: PFCON_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: pfcon-secret
                      key: PFCON_PASSWORD
                - name: SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: pfcon-secret
                      key: SECRET_KEY
              command: ["gunicorn"]
              args: ["-w", "5", "-b", "0.0.0.0:30005", "-t",  "200", "pfcon.wsgi:application"]
              volumeMounts:
                - name: storebase
                  mountPath: "/var/local/storeBase"
          volumes:
            - name: storebase
              persistentVolumeClaim:
                claimName: storebase

  - apiVersion: v1
    kind: Service
    metadata:
      name: pman-new
      labels:
        app: pman-new
        env: test
    spec:
      selector:
        app: pman-new
        env: test
      ports:
        - name: 5010-tcp
          port: 5010
          targetPort: 5010

  - apiVersion: v1
    kind: Route
    metadata:
      name: pman-new
    spec:
      port:
        targetPort: 5010-tcp
      to:
        kind: Service
        name: pman-new
        weight: 100

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: pman-new
      labels:
        app: pman-new
        env: test
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: pman-new
          env: test
      template:
        metadata:
          name: pman-new
          labels:
            app: pman-new
            env: test
        spec:
          containers:
            - name: pman-new
              image: fnndsc/pman
              ports:
                - containerPort: 5010
              env:
                - name: CONTAINER_ENV
                  value: openshift
                - name: JOB_NAMESPACE
                  value: bu-chris-fall2022
                - name: STOREBASE
                  value: "/tmp/"
                - name: SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: pman-secret
                      key: SECRET_KEY

              volumeMounts:
                - name: storebase
                  mountPath: "/var/local/storeBase"
          volumes:
            - name: storebase
              persistentVolumeClaim:
                claimName: storebase
# Consider adding resource creation for storebase persistentVolume creation here
          
labels:
  template: application-template-pfcon-openshift