apiVersion: v1
kind: Pod
metadata:
  name: chris-fs-plugin-pod
  namespace: bu-chris-fall2022
spec:
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: test-input-pvc-2
  containers:
    - name: lungs-fs-plugin
      image: fnndsc/pl-lung_cnp
      command: ["lung_cnp", "/output"]
      volumeMounts:
      - name: my-volume
        mountPath: /output
  restartPolicy: OnFailure